### ISSUE TITLE
coverage reporting is broken

### ISSUE THREAD

**Issue by jugmac00** [morepath/more.body_model#5]
... for unknown reasons (works for other repositories)

**Comment by henri-hulski** [comment]
We check here as we do in most packages for 100% coverage. Otherwise it fails. So we don't need Coveralls, which I really don't like. We can just report 100% coverage.
Here's the code from `tox.ini`:
```
[testenv:coverage]
basepython = python3
extras = test
         coverage

commands = pytest --cov --cov-fail-under=100 {posargs}
```

**Comment by jugmac00** [comment]
Thanks for the feedback!

Currently, I maintain CI for all 20+ morepath repositories, so I wanted to have the CI configuration to be uniform for all repositories, so it takes less time to maintain.

But yeah, coveralls.io is unfortunately super flaky, and most of the time works, but especially for some morepath repositories it does not work. I have encountered this problem neither in my personal repos nor in the dozens or hundreds of Zope repositories. I have found no way to debug the problem yet.

For now, I have deactivated coveralls integration, which also means we cannot show a nice 100% coverage badge on the start page :-)

**Comment by henri-hulski** [comment]
We actually tried to reach 100% for all relevant packages and removed instead the Coveralls integration which has much unnecessary overhead especially if you reach 100% coverage.
So I think the goal is to reach 100% for all packages and remove Coveralls entirely.

If you want a nice badge you can use this one: https://github.com/dbrgn/coverage-badge
